from typing import Protocol


class UiPort(Protocol):
    """What the engine asks the screen to do. Implementations must be callable from any thread."""
    def show_join(self, server: str | None, error: str | None = None) -> None: ...
    def show_preflight(self, checks: list[dict]) -> None: ...
    def start(self, seat_no: int, set_name: str, ends_at_local: float, folder: str) -> None: ...
    def set_ends_at(self, ends_at_local: float) -> None: ...
    def notice(self, text: str) -> None: ...
    def block(self, title: str, persistent: bool = False) -> None: ...
    def unblock(self) -> None: ...
    def done(self, n_files: int, at: str) -> None: ...
    def error(self, text: str) -> None: ...
    def quit(self) -> None: ...
